workflows:
android-build:
name: Android Build
instance_type: mac_mini_m2
environment:
flutter: stable
scripts:
- name: Get dependencies
script: flutter pub get
- name: Build APK
script: flutter build apk